# Site settings
title: Barger Street Group
email: info@bargerstreetgroup.com
description: > # this means to ignore newlines until "baseurl:"
  The Barger Street Group lies at the intesection of Data Science and
  Critical Incident Response.  We speak on and research Active Shooter
  and Active Threat incidents to improve survivability and recovery.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://locahost:4000" # the base hostname & protocol for your site
twitter_username: bargerstreet
github_username:  jekyll

# Build settings
markdown: kramdown
